### ISSUE TITLE
Why is this a public repo?

### ISSUE THREAD

**Issue by mikelikesbikes** [Devbootcamp/snitching-on-sinatra#21]
Seems like the current norm is that all curriculum is considered private. Any reason this challenge has been ordained as a public challenge? Is there some policy about public challenges? :v:

**Comment by mikelikesbikes** [comment]
@Devbootcamp/curriculum @Devbootcamp/curriculum-master

**Comment by dreeve** [comment]
I don't mind making it private! 

For a short time in San Francisco we were linking to the Devbootcamp version of the tutorial instead of forking for each cohort. We tried it for a few phases and I don't think there was much benefit from doing so.

On the other hand, I (personally) see a difference between challenges and "tutorials." Making a series of blog posts about this content came up in the past, so I just figured if someone wanted to use it, that's cool by me. I'll make it private for now and ask around to make sure I'm not breaking rules!

Thanks for bringing this up!
